### PR TITLE
Update and rename Department of Health (DoH) – Pass 1.csv to National…

### PR DESCRIPTION
**Pull request by tristynferreiro**
… Departments/Department of Health/Department of Health (DoH) – Pass 1.csv

#104  
Removed R's, "," and spaces and fixing dates. 
I renamed the file and put it in the correct location
I renamed some of the columns (am waiting for feedback on what to rename others)

I also split some of the columns, could you please check if the way in which I did it is alright.
There are two rows in the "Unit price" column that have descriptions, I am not sure wether or not that should be removed.
If I split the second column it will cause conflicts in row 8, 11 and 12 due to extra descriptions in that cell. It will also cause conflicts with line 11's unit price column since it gives a total amount ordered but doesn't differentiate between if it is steriprep  or Sterisol 

Thanks!

### CODE REVIEW

**Comment by jbothma** [comment]
- Items Procured including quantities per item 
  - rename to items_description
- Name of entity
  - rename to supplier_name
- Total Transaction
  - rename to order_amount_zar
- Date of delivery of goods 
  - use the new column name implementation_status I just documented
- please add a column buyer_name with value `Department of Health`
- when uploading please call the dataset `National Department of Health Pass 1`

Every dataset must have at least

- supplier_name
- order_amount_zar
- buyer_name

there should usually also be items_description - it's rare that that's not provided.

**Comment by tristynferreiro** [comment]
@jbothma should be good now?

**Comment by jbothma** [comment]
oh no! there was a misunderstanding. Not sure if the original was like this and I just missed it.

We can't have a row per item because then we're saying each item's total cost was 1343952.75 which is not the case. So we need to have exactly one row for this for now. You can keep this version for later analysis - it's very useful cleaning you've done, but it's not what we want to be loading into keepthereceipts right now


buyer_name | Date of procurement | items_description | procurement_method | supplier_name | director_names_and_surnames | Date of first registration of the entity with CIPC | Unit cost for each item | order_amount_zar | implementation_status | Indicate if the company registration includes supply of PPE as a service that they render
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Department of Health | 2020-03-05 | Shoe covers high heel (2,000)Overalls(2,000)Gloves High Risk (12,000)Latex Gloves (12,000)Aprons (3,000)Face masksFFP2 Masks (3,500)N95 masks(25,025)Googles (2,000)Powder free gloves (8,000)Clean Wipes (20)500 ml Hand Sanitizer (360)200 ml Hand Sanitizer (1,000) | Emergency procurement approvalNational Treasury Instruction no 08 of 2019/2020 | Mr First Aid Pty Ltd | 1.Catherine Dorothy Goldin2.Roy Frank Goldin3.Jason Roy Goldin4.In IT Together | 20 December 1990 | Shoe covers high heel (R144.90)Overalls (R196.00)Gloves High Risk (R1,43)Latex Gloves (R0,62)Aprons (R0,46)Face masks (R0,46)FFP2 Masks (R14.20)N95 masks (R20.67)Googles (R22.43)Powder free gloves (R0,84)Clean Wipes (R60.95)500 ml Hand Sanitizer (R67.85)200 ml Hand Sanitizer (R34,5) | 1343952.75 | 25 March 2020 | YesWholesale and retail trade

**Comment by tristynferreiro** [comment]
@jbothma Done! Sorry about that...

I also changed Date of procurement to invoice_date is that okay?

**Pull request merged**
