### PR TITLE
Create tabula-DIRCO - Information related to quotations for COVID-19 …

### PR DESCRIPTION
**Pull request by douglas86**
#57

### CODE REVIEW

**Comment by georgezee** [comment]
This needs additional work to get the entries into a single row each. See:

pr-202-comparison

**Comment by douglas86** [comment]
Should those cells be merged.

**Review by tristynferreiro — CHANGES_REQUESTED** [review]
@douglas86 Please make it look exactly like the table in the document. "Body Temperature Thermal Cameras" should be in one cell, same with "Request for quotation". Each entry should only have one row.

**Comment by douglas86** [comment]
I have changed it in this commit, won't you please see if it is right. 
https://github.com/keep-the-receipts/data-extraction/pull/300/commits/0fee541e4a723e7dee1a0e76a305d2ed776909c4

**Comment by jbothma** [comment]
How... it's not clear what you did here - this commit does not belong to a branch? could you explain what you did?

Screenshot_2020-10-28_22-10-30

What does this file look like to you? When we preview it here it looks complete broken. I'd like to understand what's happening that you're submitting files like this.

Screenshot_2020-10-28_22-10-42

**Comment by tristynferreiro** [comment]
I have extracted the file PR #398

**Pull request closed without merging**
