### PR TITLE
Create tabula-CORRECTIONAL SERVICES - SCHEDULE OF PROCUREMENT TO COMB…

### PR DESCRIPTION
**Pull request by douglas86**
#60

### CODE REVIEW

**Comment by tristynferreiro** [comment]
@douglas86 Hi there! This file cannot be merged. There are several different tables and they each need to be in their own file.  Would you be up to doing that?

**Review by tristynferreiro — CHANGES_REQUESTED** [review]
Please read the above comment

**Comment by douglas86** [comment]
I have split this document into different files with there correct file name, just have a look to see if it is correct.

**Comment by jbothma** [comment]
Where are the different files? I only see the original under Files Changed. Did you open a new pull request with the individual files?

**Pull request closed without merging**
