### PR TITLE
Create BROADBAND INFRACO - Response Procurement Spending During COVID…

### PR DESCRIPTION
**Pull request by vrautenbach**
…-19 Pandemic 20200824.csv

#90

### CODE REVIEW

**Comment by jbothma** [comment]
reviewing

**Comment by jbothma** [comment]
Awesome! 

This is great. For some reason they didn't make this a single table!

Would you feel comfortable transforming this so that these are column names? No stress if you don't  -we can do that later.

Screenshot_2020-10-03_12-55-13

**Comment by vrautenbach** [comment]
I combined the tables into one and transposed the data. 

Screenshot 2020-10-03 at 13 21 06

**Comment by CamGreen** [comment]
Thank you @vrautenbach !

**Pull request merged**
