### PR TITLE
Create tabula-SASSA - Covid 19 Procurement March 2020 - Head Office a…

### PR DESCRIPTION
**Pull request by Lean3Viljoen94**
…nd Regions PPE only-KZN

#108

6 of 11

### CODE REVIEW

**Comment by Lean3Viljoen94** [comment]
Screenshot 2020-10-03 at 13 17 14

**Comment by vrautenbach** [comment]
@Lean3Viljoen94 Good work so far. Just an issue with Row 5. It should be as close to the original as possible. Thus not separate rows, but rather one row. Are you up for trying to fix this?

**Comment by Lean3Viljoen94** [comment]
Hi @vrautenbach thanks for the review! Unfortunately, I don't have time today, but I'll have a look at it tomorrow 👍

**Comment by vrautenbach** [comment]
Perfect, thank you!

**Comment by tristynferreiro** [comment]
I fixed the issues, thank you @Lean3Viljoen94 for the work :D

**Pull request merged**
