### PR TITLE
Create tabula-NATIONAL TREASURY ENTITIES - Report on COVID-19 spendin…

### PR DESCRIPTION
**Pull request by douglas86**
#81

### CODE REVIEW

**Comment by vrautenbach** [comment]
@douglas86 I can see that this is a tricky document. I cannot accept it as is, but maybe @jbothma can give you some ideas on how to fix the tables from page 2 onwards. 

The table on page on was submitted as PR #166

**Comment by douglas86** [comment]
There were a few of my docs that I altered slightly, I just need to see if this is one of them.

**Comment by vrautenbach** [comment]
O I see, now. However, the first few lines were loaded as a separated table already. The actual table only starts on line 19. The other problem was that single cells were broken up into multiple rows. See below for an example. 
Screenshot 2020-10-25 at 17 01 57

**Comment by douglas86** [comment]
Sorry, I just want to clarify what it is you want me to sort out. Having a look at the doc, it looks like in the table section there shouldn't be any empty rows, so I should copy from line above, am I correct in saying so.

**Comment by vrautenbach** [comment]
I think this is the corresponding section. The text was combined. This should be two different columns, see below.  It looks like it might need to be re-extracted. 

Screenshot 2020-10-25 at 18 46 14

**Comment by douglas86** [comment]
OK, sure. I will have a look and come back to you on tomorrow.

**Comment by tristynferreiro** [comment]
@douglas86 I closed pull request #166 after adding in the missing row which I submitted to a new pull request. You can remove that table and its data from this file

**Comment by jbothma** [comment]
@douglas86 would you mind structuring it like follows? Importantly

- no blank lines
- the ...s mean the rest of each table
- the table on the right must also be there
- have a crack at figuring out the full name, but the Entity column is the one they actually have there - I just googled the acronym and tried to connect it to one of the entities in the first table
don't try and interpret anything like pulling company numbers out of the `Company appointed` column - just use the data they gave us, but make sure there's exactly one row per supplier and amount and item
- skip total rows

Entity | Entity | Type | Date of appointment | Goods/Services | Procurement Processes | Company appointed | Company registration number | Value
-- | -- | -- | -- | -- | -- | -- | -- | --
ASB | Accounting Standards Board | Costs on Covid-19 Activities | 28-May-20 | COVID-19 Posters | Qutations | UVO Communications |   | R414.00
ASB | Accounting Standards Board | Costs on Covid-19 Activities | Top up for May, Jun & July | MTN Topup Data - Remote working | Excisting contract | MTN |   | R2,104.00
ASB | … | … | … | … | … | … |   | …
ASB | Accounting Standards Board | Costs on PPE's | 8-May-20 | Infrared Themometer | Quotations | Alphabet Soup |   | R1,897.00
ASB | … | … | … | … | … | … | … | …
FAIS | Financial Sector Conduct Authority | Costs on Covid-19 Activities | 29-Apr-20 | Disinfection, sanitation, fumigation and deep cleaning of the office for a period of 6 months | Deviation (One supplier responded to our request) | Masana Hygiene Services (Pty) Ltd (2014/110265/07) |   | R90,098.00
FAIS | … | … | … | .. | … | … | … | …
FAIS |   | Costs on PPE's |   |   |   | Masana Hygiene Services (Pty) Ltd | 2014/110265/07 |

**Comment by douglas86** [comment]
So i sorted out the empty lines, I split the table over two separate files. So that it would be easier to see, if I did it in one file one table would be longer than the other table. This is for these two documents.
National Treasury Entities - Report on COVID-19 spending - cost of activities.csv
National Treasury Entities - Report on COVID-19 spending - cost of PPE's.csv
The contents of this commit was done to the best of my abilities, if any further problems arise, please feel free to reach out.

So I have rectified all mistake, here is the latest commit.
https://github.com/keep-the-receipts/data-extraction/pull/300/commits/3094fd156ebc18215610576e40fed028e5a2a8ab

**Comment by tristynferreiro** [comment]
Redone in another PR

**Pull request closed without merging**
