### PR TITLE
Create FREE STATE SPORTS, ARTS, CULTURE AND RECREATION.csv

### LINKED ISSUE #19: FREE STATE Sport, Arts, Culture and Recreation pass 1
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20SPORTS%2c%20ARTS%2c%20CULTURE%20AND%20RECREATION.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

### PR DESCRIPTION
**Pull request by NarothamSai**
Fixes #19 
image

### CODE REVIEW

**Comment by NarothamSai** [comment]
I have left out top 2 headings, 
**EXPENDITURE AND COMMITMENT REPORT ON EMERGENCY PROCUREMENT IN RESPONSE TO THE NATIONAL STATE OF DISASTER**
**NAME OF DEPARTMENT: …Sport, Arts, Culture and Recreation... FINANCIAL YEAR 2019/2020**
Is it OK?

**Comment by NarothamSai** [comment]
image

**Comment by jbothma** [comment]
Thanks! Please fill down the supplier name and number  each row must have a supplier and an amount.

**Comment by NarothamSai** [comment]
image
@jbothma 
Added supplier name, date and amount at each row. Please can you review?

**Comment by NarothamSai** [comment]
image

**Pull request merged**
