### PR TITLE
Update and rename tabula-STATS SA - Annexure A - Covid 10 Related Act…

### PR DESCRIPTION
**Pull request by tristynferreiro**
…ivities Procurement 31 July 2020.csv to National Departments/The Presidency/STATS SA - Annexure A - Covid 10 Related Activities Procurement 31 July 2020.csv

#51 
Cleaned data
Renamed columns

Not sure what the file should be called

### CODE REVIEW

**Comment by jbothma** [comment]
Please format invoice_date as ISO 8601 dates

**Comment by jbothma** [comment]
Looks good otherwise. Thanks!

**Comment by jbothma** [comment]
oh please add a buyer_name column

**Comment by jbothma** [comment]
The file name looks fine

**Comment by jbothma** [comment]
Screenshot_2020-11-02_20-14-35

sorry I meant the invoice_date column should be formatted like 2020-03-23 which is a the date part of the ISO-8601 format

**Comment by jbothma** [comment]
Other than that it looks good and ready to go :)

**Comment by tristynferreiro** [comment]
@jbothma I am actually laughing at the fact that I renamed the column to that instead of formatting *face palm*. Lack of sleep catching up to me lol

**Comment by tristynferreiro** [comment]
all good now?

**Comment by jbothma** [comment]
all good!

**Pull request merged**
