### PR TITLE
Create Mpumalanga COVID 19 Expenditure Report–Education.csv

### PR DESCRIPTION
**Pull request by tristynferreiro**
#5

### CODE REVIEW

**Comment by vrautenbach** [comment]
@candidcreature Thanks for the good work so far. The CSV has some issues. The heading columns do not align correctly, and the headings are also repeated in the middle of the table. If you are able to, can you please try and get the table as close to the original as possible? Thanks.

**Comment by tristynferreiro** [comment]
@vrautenbach Should be fixed!

**Comment by jbothma** [comment]
Why is there that Masibone row at the top? I think you can delete that if it's just an accident and the total row at the bottom then this looks good to go!

**Comment by tristynferreiro** [comment]
Done

**Comment by jbothma** [comment]
You're so quick! If you'd like to chat about how you can help further, say hi in zatech.co.za slack #keep-the-receipts or jd@openup.org 

Thanks for all the work so far!

JD

**Pull request merged**
