### PR TITLE
Create tabula-SASSA - Covid 19 Procurement March 2020 - Head Office a…

### PR DESCRIPTION
**Pull request by Lean3Viljoen94**
…nd Regions PPE only-EC.csv

#108

### CODE REVIEW

**Comment by Lean3Viljoen94** [comment]
Screenshot 2020-10-03 at 13 18 11

**Comment by martink-rsa** [comment]
Hi @Lean3Viljoen94 ,

Thank you for the work you have done. There are some issues that have to be rectified before the file can be merged.

1. There are empty cells where data is grouped which will be problematic. These groups can typically have the item duplicated so that it is reused for the empty cells.

For example, 

image

2. Some of the data is not in the correct column:

image

---

These changes will have to be made to the file before it can be merged.

**Review by martink-rsa — CHANGES_REQUESTED** [review]
1. Ensure that empty rows are rectified (duplicate the grouped field into the missing fields)
2. Fix data in incorrect columns

**Comment by tristynferreiro** [comment]
I have fixed the problems and updated the file with these changes

**Pull request merged**
