### PR TITLE
Create tabula-IPID - PPE PROCUREMENT.csv

### PR DESCRIPTION
**Pull request by douglas86**
#74

### CODE REVIEW

**Comment by tristynferreiro** [comment]
@douglas86 Hey, could you just make a couple fixes and then it should be good to go! (I can’t edit the file):

Could you add the column heading “No” for the first column?
Line 12 and 29 have been shifted
Line 20 and 29 are missing their number in the first column

**Comment by tristynferreiro** [comment]
@jbothma can these lines be removed or should they be left in?
Screenshot 2020-10-26 at 23 52 22

**Comment by douglas86** [comment]
They should be removed.

**Comment by tristynferreiro** [comment]
I have created a new PR #303 to fix the issues as I edit your file

**Pull request closed without merging**
