### PR TITLE
Create HIGHER EDUCATION AND TRAINING and NAT SKILLS FUND - COVID-19 P…

### PR DESCRIPTION
**Pull request by sacheen**
…ROCUREMENTS-1.csv

#105

### CODE REVIEW

**Comment by jbothma** [comment]
Awesome!

Could you fill down the merged cells so that there is one row per order total amount, with the supplier name in each?

**Comment by jbothma** [comment]
Awesome!

Could you fill down the merged cells so that there is one row per order total amount, with the supplier name in each?
Screenshot_2020-10-03_10-59-25

**Comment by jbothma** [comment]
Screenshot_2020-10-03_11-00-54

**Comment by sacheen** [comment]
Can do!

**Comment by jbothma** [comment]
should be
Screenshot_2020-10-03_11-01-33
but watch out for the number - that must be copied - filling it down would increment it! :)

**Comment by jbothma** [comment]
Just adding here because it's a great example for the FAQ - 

All columns should be repeated. If the data will no longer make sense to repeat (e.g. if one Rand amount would be repeated many times, then it suggest we should actually not be filling down and repeating the rows.

but in this case, the long text on the far right should also repeat for each row
Screenshot_2020-10-03_11-09-11

**Comment by sacheen** [comment]
@jbothma i've filled in the extra columns

**Comment by vrautenbach** [comment]
Thank for the hard work @sacheen

**Pull request merged**
