### PR TITLE
Create tabula-SENTECH SOC LIMITED - PPE SERVICE PROVIDERS AUGUST 2020…

### PR DESCRIPTION
**Pull request by 22xb**
….csv

#93

### CODE REVIEW

**Comment by jbothma** [comment]
Thanks!

Do you mind transposing it so that it has the following columns and a row for each order?


Date of procurement
PPE procured
Procurement process followed
Company awarded
Company registration number
Value of Contract
Reason for purchases

**Comment by 22xb** [comment]
Let me get to it.

**Comment by georgezee** [comment]
hey @DK-Nkabinde - would you have any chance to review that data?

**Comment by tristynferreiro** [comment]
I made the changes

**Pull request merged**
