### PR TITLE
Update and rename NATIONAL PROSECUTING AUTHORITY_PPE - 1 Apr 2020 to …

### PR DESCRIPTION
**Pull request by tristynferreiro**
…31 March 2021 - Finalized as at 07-08-2020.csv to National Departments/NATIONAL PROSECUTING AUTHORITY_PPE - 1 Apr 2020 to 31 March 2021 - Finalized as at 07-08-2020.csv

#68 

Added buyer_name column
Added items_quantity column (should this just remain apart of item_description since some fields are empty?)
renamed columns
cleaned out R's, commas, etc

### CODE REVIEW

**Comment by jbothma** [comment]
letls use `Business Unit` as `implementation_location_facility`

**Comment by jbothma** [comment]
please rename `Supplier Legal Name` to `supplier_name`

**Comment by jbothma** [comment]
let's use `RFQ Reference Number` as `order_number`

**Comment by tristynferreiro** [comment]
@jbothma I did all of that, could you please just check the name? Not too sure if it is okay :D

**Comment by jbothma** [comment]
Looks good!

**Pull request merged**
