### PR TITLE
#77 - Create 3 x CSV for 'PUBLIC ENTERPRISES - Covid19 Expenditure Report'

### LINKED ISSUE #77: Department of Public Enterprises (DPE) -  pass 1
National Department

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/PUBLIC%20ENTERPRISES%20-%2011082020%20Covid19%20Expenditure%20Report.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201104224348/http://ocpo.treasury.gov.za/COVID19/Documents/PUBLIC%20ENTERPRISES%20-%2011082020%20Covid19%20Expenditure%20Report.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

### PR DESCRIPTION
**Pull request by georgezee**
Two challenges I faced here:
1. There were 3 sections (for Service Providers, Building Sanitisation + Petty Cash) with different columns.
I exported these to separate files, adding the section name to each file.

2. There was one item that had multiple rows for the individual line items. I combined these into a single line item using line breaks, moving the quantities into the description. (see the screenshot)

data-comparison

Fixes: #77

### CODE REVIEW

**Comment by jbothma** [comment]
> There were 3 sections (for Service Providers, Building Sanitisation + Petty Cash) with different columns.
I exported these to separate files, adding the section name to each file.

That sounds perfect

**Comment by jbothma** [comment]
having the descriptions on different lines in the same cell is perfect.

it would be better to have the quantities in the quantity column on different lines, corresponding to the lines in the description column. I think! that's how I proposed in https://github.com/South-Africa-Government-Procurement/project-docs/wiki/Data-models-and-standards anyway

**Comment by georgezee** [comment]
@jbothma - that makes sense - I've moved the quantities into the correct column:

quantiies-column-adjustment

**Comment by vrautenbach** [comment]
Thanks, @georgezee

**Pull request merged**
